### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by JeroenStoffels** [cXense/cxense-spm#3]
checksum of downloaded artifact of binary target 'CxenseSDK' (f839d3f6814913d47a58d518c57e2a00f3f04053c1029bdc14a09881afb9c5fe) does not match checksum specified by the manifest (a41788306fefd9ee372ab6a1ff0eed08a539aa74f68f9205c93fb0f90d059a44)

Since today adding the SDK through SPM does not work anymore.

Should the URLs in Package.swift for the binaryTargets not also have been updated to the zips for the 1.10.1 version published yesterday? The checksums have been updated, but the URLs still point to the zips for 1.10.0

**Comment by alexey-troshkov** [comment]
@JeroenStoffels Hi. Fixed, please check.

**Comment by JeroenStoffels** [comment]
@alexey-troshkov Works, thanks!
